### ISSUE TITLE
[BUG] Outdated Pit regex

### ISSUE THREAD

**Issue by Wyvest** [boomboompower/ToggleChat#39] opened 2021-03-23 11:54 UTC
**Describe the bug**
Pit messages with prefixes like [XV-119] cannot be toggled off

**To Reproduce**
1. Disable Pit messages
2. Go into a Pit lobby
3. bug found

**Expected behavior**
normally its supposed to block it

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Mod Version: 3.0.44
 - Minecraft Version: 1.8.9

**Comment by boomboompower** [comment] 2021-03-23 22:48
Caused by an old unoptimized regex, this will be fixed soon
https://github.com/boomboompower/ToggleChat/blob/master/src/main/java/wtf/boomy/togglechat/toggles/defaults/gamemode/TypePit.java#L27

Thanks for letting me know

**Closed as completed** 2021-04-08 15:21 UTC
Labels: done, confirmed

**Comment by boomboompower** [comment] 2021-04-08 15:23
Should be fixed, I've also added the `BOUNTY` and `STREAK` messages to the Pit toggle. Let me know if you have any more questions or issues ^^ @wyvest 

This change can be tracked [here](https://github.com/boomboompower/ToggleChat/commit/4d32f759f4c9a9d92435318c42db6d1e6a36b0e8#diff-c761728562de06247adbb03255236b3b2a451870d580b0f00cfbf7b4cb55cd3f)
