### ISSUE TITLE
[BUG] Guild Messages Toggle Broken

### ISSUE THREAD

**Issue by yanlin41020** [boomboompower/ToggleChat#30] opened 2020-06-20 07:12 UTC
Guild messages toggle is broken somehow. All other toggles seems to be working though.

**Comment by boomboompower** [comment] 2020-06-20 10:47
> Guild messages toggle is broken somehow. All other toggles seems to be working though.

Thanks for letting me know, if possible I need a bit more info, after that I'll see if I can reproduce it (potentially) tomorrow.

- Can you send a message of the guild message you are receiving in chat?
- Is this occurring on the latest beta build at **https://mods.boomy.wtf/#togglechat** ?
- Does it happen with every guild message, or just a few certain ones?

---------- 

For reference I'll leave the guild file here for later - [Guild Toggle](https://github.com/boomboompower/ToggleChat/blob/master/src/main/java/me/boomboompower/togglechat/toggles/defaults/TypeGuild.java)

**Comment by yanlin41020** [comment] 2020-06-21 00:48
Sorry for such late reply. I didn't think to check my notifications in Github. 

- I still receive all guild messages with it toggled off. 
![image](https://user-images.githubusercontent.com/15373172/85214314-c26cd000-b32e-11ea-8bf8-c0d44b5f7875.png)
- Yes, I'm using the latest beta and it's still happening. I tried to go back to the previous builds and it still doesn't prevent guild messages from appearing. I never used it before until now, so I just noticed it. I also tested the other togglable options and others seems to work just fine.

**Comment by boomboompower** [comment] 2020-06-21 11:28
Comparing the code with the messages you're getting, I think it's because of the suffix/tag after users names which hypixel just added.

I'll have a new beta for this in the next few days. Thanks for again for bringing this to my attention, just have to update a few regexes :)

**Comment by yanlin41020** [comment] 2020-06-21 15:26
Okay! Looking forward to checking the beta

**Comment by boomboompower** [comment] 2020-06-22 04:55
Should be resolved in **[3.0.27](https://github.com/boomboompower/ToggleChat/releases/tag/3.0.27)** @yanlin41020

**Closed as completed by boomboompower** 2020-06-22 04:55 UTC
Labels: done, bug
